// main.cpp: Martin Pfatrisch
// Description: The program sends sensor locations generated by the location generator

#include "location_generator.h"


// Function in location_generator.h to generate a random location
struct Location init_loc(void);
// Funtion in location_generator.h to update the location with random coordinates
struct Location update_loc(struct Location);
// Function in location_generator.h to print the coordinates of a Location structure
void print_loc(struct Location, int);

/**
 * main: Main function
 * @return      [int]       0
 */
int main(void) {
  const int period = 1000;

  // Array of locations
  struct Location locs[10];

  // Initialize locations
  for(int i = 0; i < 10; i++) {
    locs[i] = init_loc();
  }

  while(1) {
    for(int i = 0; i < 10; i++) {
      locs[i] = update_loc(locs[i]);
      print_loc(locs[i], i);
    }

    std::this_thread::sleep_for(std::chrono::milliseconds(period));
  }

  return 0;
}
